### ISSUE TITLE
Asset browser uses std methods to create and remove directories

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#144]
> You can't use methods from `std::fs` like `create_dir_all` and `remove_dir_all`. 
> The `AssetWriter` exposes a method to delete a directory: https://docs.rs/bevy/0.15.0-rc.2/bevy/asset/io/trait.AssetWriter.html#tymethod.remove_directory so you should use this one instead.
> 
> It doesn't have yet a method to create a directory, you should first add it to Bevy

_Originally posted by @mockersf in https://github.com/bevyengine/bevy_editor_prototypes/issues/143#issuecomment-2453507108_

**Comment by hcabel** [comment]
I thought this would be out of the scope for the AssetWriter.
Since it's not something that's necessary for games.

But ok yeah I'll do that then :) 

BTW I've used the file system for the launcher too, to create a cache file where all the project location is stored.

Does that make sense to use the AssetWritter for this too? If so should I add the cache directory (`%localappdata%/[crate_name]/`, `~/.cache/[crate_name]/`, `~/LibrarySomething/cache/[crate_name]/`) as an AssetSource?
