### ISSUE TITLE
Panes glitching / bugging on pane and window resize

### ISSUE THREAD

**Issue by Dokkae6949** [bevyengine/bevy_editor_prototypes#91]
When resizing a pane it sometimes glitches out and it seems quite laggy.
Also when fullscreening the editor nothing updates anymore and the program freezes.

https://github.com/user-attachments/assets/cc8f15f9-0d13-4004-96ba-94ffacefe62a

**Comment by tim-blackbird** [comment]
The jittering specifically happens to the viewport pane, presumable because something about the way layout is done on images is wrong somehow in bevy_ui

The other issue is new to me, I can't think of any code here off the top of my head that could cause that

**Comment by hcabel** [comment]
Seems that the jittering happened because of some kind of miss alignment/calculation based on the window size.
Here my scroll bar is clipped off the window, that's when the jitter happend
![Image](https://github.com/user-attachments/assets/18047fa9-43d7-49b0-82fd-a9cd96375f39)

And here I just resized the window a  bit which made the jitter stopped and my scroll_bar is showing as expected 
![Image](https://github.com/user-attachments/assets/4e4e982b-0fde-4b09-a42a-ee42d0bcc596)
